language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
before_install:
  - gem install bundler
before_script:
  - ./bin/literals
  - bundle exec appraisal update
script: bundle exec appraisal rspec
